import{a as x,S as b,i as l}from"./assets/vendor-C4-ZuMk8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))m(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&m(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function m(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const v="46873247-b56a65fb4c08f29194ce1856e",E="https://pixabay.com/api/";async function f(o,s){return(await x.get(E,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}})).data}function p(o){const s=document.getElementById("gallery"),i=o.map(({webformatURL:e,largeImageURL:t,tags:r,likes:u,views:h,comments:y,downloads:L})=>`
    <a href="${t}" class="gallery-item">
      <img src="${e}" alt="${r}" />
      <div class="info">
        <p class="info-text">Likes: ${u}</p>
        <p class="info-text">Views: ${h}</p>
        <p class="info-text">Comments: ${y}</p>
        <p class="info-text">Downloads: ${L}</p>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",i),new b(".gallery-item").refresh()}const g=document.getElementById("search-form"),C=document.getElementById("gallery"),d=document.getElementById("loader"),a=document.getElementById("load-more-btn");let c=1,n="";g.addEventListener("submit",async o=>{if(o.preventDefault(),n=g.elements.query.value.trim(),c=1,!n){l.warning({position:"topRight",message:"Please enter a search query.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"});return}C.innerHTML="",a.classList.add("hidden"),d.classList.remove("hidden");try{const s=await f(n,c);p(s.hits),s.hits.length===15&&a.classList.remove("hidden")}catch(s){console.error("Error loading more images:",s),l.error({position:"topRight",message:"Failed to load images. Try again.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"})}finally{d.classList.add("hidden")}});a.addEventListener("click",async()=>{c+=1,d.classList.remove("hidden"),document.querySelector(".loader").style.top="96%",a.classList.add("hidden");try{const o=await f(n,c);p(o.hits),o.hits.length<15&&(a.classList.add("hidden"),l.info({position:"topRight",message:"No more images to load.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"}))}catch{l.error({position:"topRight",message:"Failed to load images. Try again.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"})}finally{d.classList.add("hidden"),a.classList.remove("hidden")}});
//# sourceMappingURL=index.js.map
