import{a as x,S as v,i as l}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))m(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&m(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function m(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const E="46873247-b56a65fb4c08f29194ce1856e",C="https://pixabay.com/api/";async function f(s,o){return(await x.get(C,{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}function p(s){const o=document.getElementById("gallery"),a=s.map(({webformatURL:e,largeImageURL:t,tags:i,likes:u,views:y,comments:L,downloads:b})=>`
    <a href="${t}" class="gallery-item">
      <img src="${e}" alt="${i}" />
      <div class="info">
        <p class="info-text">Likes: ${u}</p>
        <p class="info-text">Views: ${y}</p>
        <p class="info-text">Comments: ${L}</p>
        <p class="info-text">Downloads: ${b}</p>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",a),new v(".gallery-item").refresh()}const g=document.getElementById("search-form"),h=document.getElementById("gallery"),c=document.getElementById("loader"),r=document.getElementById("load-more-btn");let d=1,n="";g.addEventListener("submit",async s=>{if(s.preventDefault(),n=g.elements.query.value.trim(),d=1,!n){l.warning({position:"topRight",message:"Please enter a search query.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"});return}h.innerHTML="",r.classList.add("hidden"),c.classList.remove("hidden");try{const o=await f(n,d);p(o.hits),o.hits.length===15&&r.classList.remove("hidden")}catch(o){console.error("Error loading more images:",o),l.error({position:"topRight",message:"Failed to load images. Try again.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"})}finally{c.classList.add("hidden")}});r.addEventListener("click",async()=>{d+=1,c.classList.remove("hidden"),document.querySelector(".loader").style.top="96%",r.classList.add("hidden");try{const s=await f(n,d);p(s.hits),w(),s.hits.length<15?(r.classList.add("hidden"),l.info({position:"topRight",message:"No more images to load.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"})):r.classList.remove("hidden")}catch{l.error({position:"topRight",message:"Failed to load images. Try again.",messageSize:"16",backgroundColor:"#ef4040",messageColor:"#fafafb",maxWidth:"432px",messageLineHeight:"88px"})}finally{c.classList.add("hidden")}});function w(){const{height:s}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
